;**********************************************************************
;                                                                     *
;    Filename:	    rc5lib.inc                                        *
;    Date:                                                            *
;    File Version:                                                    *
;                                                                     *
;    Author:        el@jap.hu                                         *
;                   http://jap.hu/electronic/                         *
;**********************************************************************

	EXTERN rc5_receive
	EXTERN rc5_tog_dev, rc5_command
